Fix network resolution errors at startup
Starting this container can fail at certbot initialization with this
error (reported at the end of /var/log/letsencrypt/letsencrypt.log):

   HTTPSConnectionPool(host='acme-v02.api.letsencrypt.org', port=443):
   Max retries exceeded with url: /directory "[Errno -3] Try again"

which sounds like a possible DNS resolution problem.

However, by logging into the container after the error above, a simple:

   wget https://acme-v02.api.letsencrypt.org/directory

usually works. It works also the exact same certbot command
logged in /var/log/letsencrypt/letsencrypt.log.

This has been verified happening while installing the contained on a
QNAP NAS with a bridged network setup.

Turns out that a small delay right before running network access
operations (e.g. running certbot) fixes all the issues.

Add a tight look to ckeck for a valid resolution of ACMESERVER to be
available. Report error in case we cannot resolve the server withing
1min. Otherwise, continue with the init scriot, as soon as nslook is
happy.

Signed-off-by: Patrick Bellasi <patrick.bellasi@matbug.net>

diff --git a/root/etc/cont-init.d/50-config b/root/etc/cont-init.d/50-config
--- a/root/etc/cont-init.d/50-config
+++ b/root/etc/cont-init.d/50-config
@@ -139,6 +139,15 @@ else
   ACMESERVER="https://acme-v02.api.letsencrypt.org/directory"
 fi
 
+# waiting for network to settle
+ACMEHOST=$(echo $ACMESERVER | awk -F/ '{print $3}')
+echo "Waiting (up to 1min) for [$ACMEHOST] to be reachable..."
+timeout 1m bash -c "until nslookup $ACMEHOST >/dev/null; do sleep 1; done"
+if [ $? -eq 1 ]; then
+  echo "ERROR: Cannot resolv $ACMEHOST"
+  sleep infinity
+fi
+
 # figuring out url only vs url & subdomains vs subdomains only
 if [ -n "$SUBDOMAINS" ]; then
   echo "SUBDOMAINS entered, processing"
